# Generated by Django 2.2.5 on 2019-09-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsAccountTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('key_id', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CfAccountTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DnspodAccountTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
            ],
        ),
    ]
