# Generated by Django 2.2.5 on 2019-09-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwsAccountTb',
        ),
    ]
