# Generated by Django 2.2.5 on 2019-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0002_delete_awsaccounttb'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32)),
                ('req_ip', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=32)),
                ('pre_rec', models.CharField(max_length=256)),
                ('now_rec', models.CharField(max_length=256)),
                ('action', models.CharField(choices=[('change', '修改'), ('add', '新增'), ('delete', '删除')], default='change', max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
