# Generated by Django 2.2.5 on 2019-09-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0003_alterhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlterHistory',
            new_name='AlterHistoryTb',
        ),
    ]
