# Generated by Django 2.2.5 on 2019-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0005_cdnaccounttb_domaindetectgrouptb_domaintb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoaminProjectTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField(choices=[(0, 'APP下载专用域名'), (1, '凤凰彩票静态域名'), (6, '凤凰彩票后台域名'), (5, '凤凰体彩主站域名'), (3, '凤凰体育静态域名'), (2, '瑞银体育静态域名'), (4, 'JAVA彩票静态域名')], unique=True)),
                ('domain', models.ManyToManyField(to='domainns.DomainTb')),
            ],
        ),
    ]
