# Generated by Django 2.2.5 on 2019-09-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0006_doaminprojecttb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaintb',
            name='cdn',
        ),
    ]
