# Generated by Django 2.2.5 on 2019-09-23 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0007_remove_domaintb_cdn'),
    ]

    operations = [
        migrations.CreateModel(
            name='domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('product', models.IntegerField(choices=[(0, '公共产品[pub]'), (12, '凤凰[fenghuang]'), (16, '勇士[warrior]'), (27, '瑞银[ruiyin|UBS]'), (26, 'JAVA'), (101, '越众棋牌')], default=12)),
                ('customer', models.IntegerField(choices=[(29, '公共客户[pub]'), (1, '阿里[ali]'), (2, '光大[guangda]'), (34, '恒达[hengda]'), (3, '乐盈|熊猫[leying]'), (4, '彩投[caitou]'), (5, '天天[tiantian]'), (6, '三德|富豪|668[sande]'), (7, 'uc彩票[uc]'), (10, 'ag彩[agcai]'), (23, '亿腾[yiteng]'), (11, '万游[klc]'), (39, '68彩[68bet]'), (40, '567彩[567bet]'), (41, '专业盘彩票[zyp]'), (42, '飞信[feixin]'), (43, '世彩堂[sct]'), (8, '谷歌[9393cp]'), (9, '苹果[188cp|3535]'), (19, '芒果[1717cp]'), (21, '乐都城[ldc]'), (36, '瑞银[ruiyin|UBS]'), (37, '勇士[warrior]'), (38, '体彩[tc]'), (13, '钻石[le7|diamond]'), (32, '世德[shide]'), (33, '图腾[tuteng]'), (31, '恒隆[henglong]'), (35, '迪拜吧[dibaiba]'), (101001, 'BB棋牌'), (101002, '汪汪棋牌')])),
                ('content', models.CharField(blank=True, max_length=128)),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1)),
                ('cf_content', models.CharField(blank=True, max_length=128)),
                ('ws_content', models.CharField(blank=True, max_length=128)),
                ('ng_content', models.CharField(blank=True, max_length=128)),
                ('auto_m_dns', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=0)),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='解析最后修改日期')),
            ],
        ),
        migrations.AlterField(
            model_name='DoaminProjectTb',
            name='domain',
            field=models.ManyToManyField(to='domainns.domains'),
        ),
        migrations.RenameModel(
            old_name='CdnAccountTb',
            new_name='cdn_account_t',
        ),
        migrations.RenameModel(
            old_name='DoaminProjectTb',
            new_name='cdn_proj_t',
        ),
        migrations.RenameModel(
            old_name='DomainDetectGroupTb',
            new_name='groups',
        ),
        migrations.DeleteModel(
            name='DomainTb',
        ),
        migrations.AddField(
            model_name='domains',
            name='cdn',
            field=models.ManyToManyField(blank=True, to='domainns.cdn_account_t'),
        ),
        migrations.AddField(
            model_name='domains',
            name='cf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domainns.CfAccountTb'),
        ),
        migrations.AddField(
            model_name='domains',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainns.groups'),
        ),
    ]
