# Generated by Django 2.2.5 on 2019-09-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0008_auto_20190923_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cdn_proj_t',
        ),
    ]
