# Generated by Django 2.2.5 on 2019-09-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0009_delete_cdn_proj_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='cdn',
        ),
    ]
