# Generated by Django 2.2.5 on 2019-09-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0010_remove_domains_cdn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='group',
        ),
    ]
