# Generated by Django 2.2.5 on 2019-09-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0011_remove_domains_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='cdn',
            field=models.ManyToManyField(blank=True, to='domainns.cdn_account_t'),
        ),
        migrations.AddField(
            model_name='domains',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainns.groups'),
            preserve_default=False,
        ),
    ]
