# Generated by Django 2.2.5 on 2019-09-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0012_auto_20190923_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='group',
        ),
    ]
