# Generated by Django 2.2.5 on 2019-09-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0014_domains_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cdn_account_t',
            new_name='CdnAccountTb',
        ),
        migrations.RenameModel(
            old_name='groups',
            new_name='DomainDetectGroupTb',
        ),
        migrations.RenameModel(
            old_name='domains',
            new_name='DomainTb',
        ),
    ]
