# Generated by Django 2.2.5 on 2019-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0016_auto_20190923_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='doaminprojecttb',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1),
        ),
    ]
