# Generated by Django 2.2.5 on 2019-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0017_doaminprojecttb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfaccounttb',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1),
        ),
        migrations.AddField(
            model_name='dnspodaccounttb',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1),
        ),
    ]
