# Generated by Django 2.2.5 on 2019-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='telegram_user_id_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1)),
            ],
            options={
                'unique_together': {('user', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='telegram_chat_group_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('group_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1)),
            ],
            options={
                'unique_together': {('group', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='department_user_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('department', models.CharField(default='未知组', max_length=32)),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1)),
                ('user', models.ManyToManyField(db_constraint=False, to='detect.telegram_user_id_t')),
            ],
            options={
                'unique_together': {('name', 'department')},
            },
        ),
    ]
