# Generated by Django 2.2.5 on 2019-09-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='telegram_user_id_t',
            new_name='TelegramUserIdTb',
        ),
    ]
