# Generated by Django 2.2.5 on 2019-09-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20190915_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department_user_t',
            new_name='DepartmentUserTb',
        ),
    ]
