# Generated by Django 2.2.5 on 2019-09-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_auto_20190915_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='telegram_chat_group_t',
            new_name='TelegramChatGroupTb',
        ),
    ]
