# Generated by Django 2.2.5 on 2019-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_auto_20190915_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchatgrouptb',
            name='group_id',
            field=models.CharField(max_length=32),
        ),
    ]
