# Generated by Django 2.2.5 on 2019-09-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weburifirstleveltb',
            name='icon',
            field=models.CharField(max_length=32, null=True, verbose_name='layui图标'),
        ),
        migrations.AlterField(
            model_name='weburisecondleveltb',
            name='icon',
            field=models.CharField(max_length=32, null=True, verbose_name='layui图标'),
        ),
        migrations.AlterField(
            model_name='weburithirdleveltb',
            name='icon',
            field=models.CharField(max_length=32, null=True, verbose_name='layui图标'),
        ),
    ]
