# Generated by Django 2.2.5 on 2019-09-16 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0004_auto_20190916_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebUriPermissionsTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weburifirst_l', models.ManyToManyField(blank=True, to='control.WebUriFirstLevelTb', verbose_name='第一级路由权限')),
                ('weburisecond_l', models.ManyToManyField(blank=True, to='control.WebUriSecondLevelTb', verbose_name='第二级路由权限')),
                ('weburithird_l', models.ManyToManyField(blank=True, to='control.WebUriThirdLevelTb', verbose_name='第三级路由权限')),
            ],
        ),
    ]
