# Generated by Django 2.2.5 on 2019-09-16 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_userweburipermissionstb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweburipermissionstb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
