# Generated by Django 2.2.5 on 2019-09-16 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0006_auto_20190916_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebUriGroupPermissionsTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='组名')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('weburifirst_l', models.ManyToManyField(blank=True, to='control.WebUriFirstLevelTb', verbose_name='第一级路由权限')),
                ('weburisecond_l', models.ManyToManyField(blank=True, to='control.WebUriSecondLevelTb', verbose_name='第二级路由权限')),
                ('weburithird_l', models.ManyToManyField(blank=True, to='control.WebUriThirdLevelTb', verbose_name='第三级路由权限')),
            ],
        ),
    ]
