# Generated by Django 2.2.5 on 2019-09-16 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_userweburigrouppermissionstb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweburipermissionstb',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
