# Generated by Django 2.2.5 on 2019-09-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20190916_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweburigrouppermissionstb',
            name='users',
        ),
        migrations.AddField(
            model_name='userweburipermissionstb',
            name='weburigroup_permissions',
            field=models.ManyToManyField(blank=True, to='control.UserWebUriGroupPermissionsTb', verbose_name='路由组权限'),
        ),
    ]
