# Generated by Django 2.2.5 on 2019-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20190916_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUriTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='接口名称')),
                ('uri', models.CharField(blank=True, default='', max_length=128, verbose_name='接口路径')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='是否启用')),
            ],
        ),
        migrations.AddField(
            model_name='userweburigrouppermissionstb',
            name='weburi_permissions',
            field=models.ManyToManyField(blank=True, to='control.WebUriTb', verbose_name='接口权限'),
        ),
        migrations.AddField(
            model_name='userweburipermissionstb',
            name='weburi_permissions',
            field=models.ManyToManyField(blank=True, to='control.WebUriTb', verbose_name='接口权限'),
        ),
    ]
