# Generated by Django 2.2.5 on 2019-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20190916_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweburigrouppermissionstb',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='是否启用'),
        ),
    ]
