# Generated by Django 2.2.5 on 2019-09-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_userweburigrouppermissionstb_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWebUriGroupPermissionsTb',
            new_name='UserGroupPermissionsTb',
        ),
    ]
