# Generated by Django 2.2.5 on 2019-09-16 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0012_auto_20190916_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWebUriPermissionsTb',
            new_name='UserPermissionsTb',
        ),
    ]
