# Generated by Django 2.2.5 on 2019-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainns', '0002_delete_awsaccounttb'),
        ('control', '0013_auto_20190916_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrouppermissionstb',
            name='cf_account_p',
            field=models.ManyToManyField(blank=True, to='domainns.CfAccountTb', verbose_name='CloudFlare账号 权限'),
        ),
        migrations.AddField(
            model_name='usergrouppermissionstb',
            name='dnspod_account_p',
            field=models.ManyToManyField(blank=True, to='domainns.DnspodAccountTb', verbose_name='DnsPod账号 权限'),
        ),
        migrations.AddField(
            model_name='userpermissionstb',
            name='cf_account_p',
            field=models.ManyToManyField(blank=True, to='domainns.CfAccountTb', verbose_name='CloudFlare账号 权限'),
        ),
        migrations.AddField(
            model_name='userpermissionstb',
            name='dnspod_account_p',
            field=models.ManyToManyField(blank=True, to='domainns.DnspodAccountTb', verbose_name='DnsPod账号 权限'),
        ),
    ]
