# Generated by Django 2.2.5 on 2019-09-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_auto_20190916_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermissionstb',
            old_name='weburigroup_permissions',
            new_name='usergroup_p',
        ),
    ]
