# Generated by Django 2.2.5 on 2019-09-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_auto_20190916_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergrouppermissionstb',
            old_name='weburi_permissions',
            new_name='weburi_p',
        ),
        migrations.RenameField(
            model_name='userpermissionstb',
            old_name='weburi_permissions',
            new_name='weburi_p',
        ),
    ]
